@contentType = application/json
@baseUrl = http://localhost:3010/monitor-server

###
# @name ping
GET {{baseUrl}}/ping
Content-Type:  {{contentType}}


###
# @name list-service
GET {{baseUrl}}/services


###
# @name list-machine
GET {{baseUrl}}/machines?service=liberator-api


###
# @name get-path
GET {{baseUrl}}/path?service=liberator-api


###
# @name server-status
POST {{baseUrl}}/server-status
Content-Type:  {{contentType}}

{
    "machineIds": ["machine_01", "machine_02"]
}


###
# @name request-data
POST {{baseUrl}}/request
Content-Type: {{contentType}}

{
    "interval": "1 week",
    "totalPoint": 33
    # "services": ["jobA"],
    # "machines": ["machine_03"]
}

### 
# @name get-cpu-usage
POST {{baseUrl}}/cpu-usage
Content-Type: {{contentType}}

{
    "interval": "3 hours",
    "totalPoint": 10 
    # "machines": ["machine_05"]
}


### 
# @name get-mem-usage
POST {{baseUrl}}/mem-usage
Content-Type: {{contentType}}

{
    "interval": "1 week",
    "totalPoint": 500
    # "machineIds": ["machine_02"]
}


### 
# @name get-rx-network-usage
POST {{baseUrl}}/rx-network-usage
Content-Type: {{contentType}}

{
    "interval": "1 week",
    "totalPoint": 500
    # "machineIds": ["machine_02"]
}


### 
# @name get-tx-network-usage
POST {{baseUrl}}/tx-network-usage
Content-Type: {{contentType}}

{
     "interval": "1 week",
    "totalPoint": 500
    # "machineIds": ["machine_02"]
}

###
# @name error-req-ratio
POST {{baseUrl}}/request-error-ratio
Content-Type: {{contentType}}

{
    "interval": "7 day"
    # "machines": ["machine_00"]
}

###
# @name error-rate
POST {{baseUrl}}/error-rate
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08 21:27:53.602+00",
    "endTime" : "2024-12-08 21:27:53.602+00",
    "resolution": "1 hour"
    # "services": [],
    # "machines": [],
    # "controllers": []
}



###
# @name path-ratio
POST {{baseUrl}}/path-ratio
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08 21:27:53.602+00",
    "endTime" : "2024-12-08 21:27:53.602+00"
    # "services": [],
    # "machines": [],
    # "controllers": []
}


### 
# @name error-ranking
GET {{baseUrl}}/error-ranking?service=liberator-api


###
# @name response-avg
POST {{baseUrl}}/avg-response
Content-Type: {{contentType}}

{
    "interval": "1 week",
    "totalPoint": 500
    # "services": ["jobA"],
    # "machineIds": ["machine_02", "machine_01"]
}

# ###
# # @name response-dist
# POST {{baseUrl}}/dist-response
# Content-Type: {{contentType}}

# {
#     "startTime": "2024-10-07 21:27:53.602+00",
#     "endTime": "2024-12-30 21:28:53.602+00" ,
#     "resolution": "1 second"
#     # "services": ["liberator-api"],
#     # "controllers": ["AppController"]
# }

# ###
# # @name server-timeline
# POST {{baseUrl}}/server-timeline
# Content-Type: {{contentType}}

# {
#     "startTime": "2024-10-07 21:27:53.602+00",
#     "endTime": "2024-12-30 21:28:53.602+00" ,
#     "services": "jobA",
#     "machineIds": ["machine_01", "machine_02"]
# }

###
# @name create-alert
POST {{baseUrl}}/create-alert
Content-Type: {{contentType}}

{
    "name": "server down",
    "type": "server_down",
    "duration": "1 minute",
    "message": "${machine} is down!!",
    "silence_time": "1 day",
    "services": ["aa-backend"]
}

###
# @name create-recipient
POST {{baseUrl}}/create-recipient
Content-Type: {{contentType}}

{
    "name": "telegram_bot",
    "detail": {
        "app": "telegram",
        "token": "7731705891:AAEg9pvLFjTAlnUvzhhN2QpmgImIm14FUpM",
        "url": "https://api.telegram.org/bot",
        "room": "-4565250427"
    }
}


###
# @name create-group
POST {{baseUrl}}/create-group
Content-Type: {{contentType}}

{
    "name": "telegram_bot",
    "recipients": [1,2,3]
}


###
# @name add-recipient-to-group
POST {{baseUrl}}/add-recipient-to-group
Content-Type: {{contentType}}

{
    "groupId": 1,
    "recipients": [1,2,3,4]
}


###
# @name remove-recipient-from-group
POST {{baseUrl}}/remove-recipient-from-group
Content-Type: {{contentType}}

{
    "groupId": 1,
    "recipients": [3,4]
}


###
# @name get-alert-history
GET {{baseUrl}}/alert-rules
Content-Type: {{contentType}}


###
# @name get-recipients
GET {{baseUrl}}/recipients?ruleId=
Content-Type: {{contentType}}



###
# @name disable-rule
GET {{baseUrl}}/disable-rule?ruleId=1
Content-Type: {{contentType}}

###
# @name enable-rule
GET {{baseUrl}}/enable-rule?ruleId=1
Content-Type: {{contentType}}

###
# @name delete-rule
GET {{baseUrl}}/delete-rule?ruleId=2
Content-Type: {{contentType}}


###
# @name delete-recipient
GET {{baseUrl}}/delete-recipient?recipientId=2
Content-Type: {{contentType}}


###
# @name get-recipient-from-group
GET {{baseUrl}}/get-recipient-from-group?groupId=1

###
# @name add-group-to-rule
POST {{baseUrl}}/add-group-to-rule
Content-Type: {{contentType}}

{
    "ruleId": 1,
    "groupId": 1
}


###
# @name remove-groupfrom-rule
POST {{baseUrl}}/add-group-to-rule
Content-Type: {{contentType}}

{
    "ruleId": 1,
    "groupId": 1
}
