@contentType = application/json
@baseUrl = http://localhost:3010/monitor-server

###
# @name ping
GET {{baseUrl}}/ping
Content-Type:  {{contentType}}


###
# @name collectMetrics
POST {{baseUrl}}/collectMetrics
Content-Type:  {{contentType}}

{
    "requestRate": {
        "data": [
            {
                "created": 1,
                "job": "job_A",
                "machineId": "machine_01",
                "count": 10,
                "path": "path_a"
            },
            {
                "created": 2,
                "job": "job_A",
                "machineId": "machine_01",
                "count": 10,
                "path": "path_a"
            },
            {
                "created": 3,
                "job": "job_A",
                "machineId": "machine_01",
                "count": 10,
                "path": "path_a"
            }
        ]
    }
}

###
# @name list-service
GET {{baseUrl}}/services


###
# @name list-machine
GET {{baseUrl}}/machines?service=jobA


###
# @name get-path
GET {{baseUrl}}/path?service=jobA


###
# @name server-status
POST {{baseUrl}}/server-status
Content-Type:  {{contentType}}

{
    "machineIds": ["machine_01", "machine_02"]
}

###
# @name request-data
POST {{baseUrl}}/request
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08 21:27:53.602+00",
    "endTime": "2024-10-10 21:28:53.602+00" ,
    "resolution": "1 hour"
    # "services": ["jobA"],
    # "machineIds": ["machine_02", "machine_01"]
}

### 
# @name get-cpu-usage
POST {{baseUrl}}/cpu-usage
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08T16:00:00.000Z",
    "endTime": "2024-10-09T23:00:00.000Z" ,
    "resolution": "1 hour"
    # "machineIds": ["machine_02"]
}

### 
# @name get-mem-usage
POST {{baseUrl}}/mem-usage
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08 21:27:53.602+00",
    "endTime": "2024-10-29 21:28:53.602+00" ,
    "resolution": "1 hour"
    # "machineIds": ["machine_02"]
}

### 
# @name get-rx-network-usage
POST {{baseUrl}}/rx-network-usage
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08 21:27:53.602+00",
    "endTime": "2024-10-09 21:28:53.602+00" ,
    "resolution": "1 hour"
    # "machineIds": ["machine_02"]
}


### 
# @name get-tx-network-usage
POST {{baseUrl}}/tx-network-usage
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08 21:27:53.602+00",
    "endTime": "2024-10-09 21:28:53.602+00" ,
    "resolution": "1 hour"
    # "machineIds": ["machine_02"]
}

###
# @name error-req
GET {{baseUrl}}/error-req?service=jobB

### 
# @name error-ranking
GET {{baseUrl}}/error-ranking?service=liberator-api

###
# @name response-avg
POST {{baseUrl}}/avg-response
Content-Type: {{contentType}}

{
    "startTime": "2024-10-08 21:27:53.602+00",
    "endTime": "2024-10-10 21:28:53.602+00" ,
    "resolution": "1 hour"
    # "services": ["jobA"],
    # "machineIds": ["machine_02", "machine_01"]
}

###
# @name response-dist
POST {{baseUrl}}/dist-response
Content-Type: {{contentType}}

{
    "startTime": "2024-10-07 21:27:53.602+00",
    "endTime": "2024-10-30 21:28:53.602+00" ,
    "resolution": "1 second"
    # "services": ["liberator-api"],
    # "controllers": ["AppController"]
}

###
# @name server-timeline
POST {{baseUrl}}/server-timeline
Content-Type: {{contentType}}

{
    "startTime": "2024-10-07 21:27:53.602+00",
    "endTime": "2024-10-30 21:28:53.602+00" ,
    "services": "jobA",
    "machineIds": ["machine_01", "machine_02"]
}

###
# @name create-alert
POST {{baseUrl}}/create-alert
Content-Type: {{contentType}}

{
    "name": "alert_cpu",
    "expression": "AVG(CPU{services=[liberator-api],machines=[machine_03]}) > AVG(CPU, "1 days")",
    "duration": "5 seconds",
    "severity": "danger"
}

###
# @name create-recipient
POST {{baseUrl}}/create-recipient
Content-Type: {{contentType}}

{
    "app": "telegram",
    "token": "7731705891:AAEg9pvLFjTAlnUvzhhN2QpmgImIm14FUpM",
    "url": "https://api.telegram.org/bot",
    "room": "-4565250427"
}


###
# @name add-recipient-to-alert
POST {{baseUrl}}/add-recipient
Content-Type: {{contentType}}

{
    "ruleId": "1",
    "recipientIds": ["1", "2"]
}