version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=monitor_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  monitorserver:
    image: monitorserver:latest
    command: node dist/main.js
    ports:
      - '3010:3010'
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/monitor_server?schema=public
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=host.docker.internal
      - PGPORT=5432
      - PGDATABASE=monitor_server_
      - TELEGRAM_URL=https://api.telegram.org/bot
      - TELEGRAM_TOKEN=7731705891:AAEg9pvLFjTAlnUvzhhN2QpmgImIm14FUpM
      - TELEGRAM_CHAT_ID=-4565250427
