version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    command: postgres -c shared_preload_libraries=timescaledb
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=monitor_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  grafana:
    image: grafana/grafana:10.0.2
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/
